# Generated by Django 3.2.6 on 2021-09-25 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('brief', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'db_table': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('changeEmail', '修改邮箱')], max_length=20, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2021, 9, 25, 14, 29, 0, 101311), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': ' 邮箱验证码',
                'verbose_name_plural': ' 邮箱验证码',
                'db_table': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='organization_structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='组织架构名称')),
                ('brief', models.CharField(blank=True, max_length=500, null=True, verbose_name='组织架构简介')),
            ],
            options={
                'verbose_name': '组织架构表',
                'verbose_name_plural': '组织架构表',
                'db_table': '组织架构表',
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('org_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.organization_structure')),
            ],
            options={
                'verbose_name': '职位表',
                'verbose_name_plural': '职位表',
                'db_table': '职位表',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('realname', models.CharField(default='', max_length=50)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(default='未知', max_length=2)),
                ('avatar', models.CharField(default='https://api.sunweihu.com/api/sjtx/api.php?lx=a1', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('userEmail', models.EmailField(default='', max_length=254)),
                ('induction_date', models.DateField(auto_now_add=True, verbose_name='注册日期')),
                ('is_formal', models.BooleanField(default=False, verbose_name='是否已转正')),
                ('status', models.IntegerField(choices=[(1, '已离职'), (0, '正常')], default=0)),
                ('is_comp_rest', models.BooleanField(blank=True, null=True, verbose_name='是否签订竞业限制')),
                ('base_salary', models.IntegerField(default=0, verbose_name='基本工资')),
                ('user_type', models.CharField(default='普通成员', max_length=4)),
                ('work_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': '用户',
            },
        ),
        migrations.CreateModel(
            name='training_time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='名称')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='培训开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='培训结束时间')),
                ('talk_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '培训时间表',
                'verbose_name_plural': '培训时间表',
                'db_table': '培训时间表',
            },
        ),
        migrations.CreateModel(
            name='specific_device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(0, '正常'), (1, '故障'), (2, '维修中')], default=0, max_length=4)),
                ('Equipment_serial_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Running_state', models.CharField(choices=[(1, '运行中'), (0, '休息')], default=0, max_length=4)),
                ('type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.device_type')),
            ],
            options={
                'verbose_name': '具体设备表',
                'verbose_name_plural': '具体设备表',
                'db_table': '具体设备表',
            },
        ),
        migrations.CreateModel(
            name='salary_pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='发放时间')),
                ('salary', models.IntegerField(default=0, verbose_name='发放金额')),
                ('type', models.IntegerField(choices=[(0, '基本工资'), (1, '年终奖')], default=0)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '工资发放表',
                'verbose_name_plural': '工资发放表',
                'db_table': '工资发放表',
            },
        ),
        migrations.CreateModel(
            name='punch_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_time', models.TimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '打卡记录表',
                'verbose_name_plural': '打卡记录表',
                'db_table': '打卡记录表',
            },
        ),
        migrations.CreateModel(
            name='person2device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.device_type')),
                ('person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '人员设备表',
                'verbose_name_plural': '人员设备表',
                'db_table': '人员设备表',
            },
        ),
        migrations.CreateModel(
            name='overtime_approval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='加班申请开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='加班申请结束时间')),
                ('description', models.CharField(default='', max_length=500, verbose_name='原因')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '加班审批表',
                'verbose_name_plural': '加班审批表',
                'db_table': '加班审批表',
            },
        ),
        migrations.CreateModel(
            name='leave_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='请假开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='请假结束时间')),
                ('description', models.CharField(default='', max_length=500, verbose_name='原因')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '请假记录表',
                'verbose_name_plural': '请假记录表',
                'db_table': '请假记录表',
            },
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eva_time', models.TimeField(auto_now_add=True, verbose_name='考核时间')),
                ('eva_grade', models.CharField(default='', max_length=4)),
                ('content', models.CharField(default='', max_length=4, verbose_name='考核评价内容')),
                ('eva_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='eva_id', to='api.user')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.user')),
            ],
            options={
                'verbose_name': '考核评价表',
                'verbose_name_plural': '考核评价表',
                'db_table': '考核评价表',
            },
        ),
        migrations.CreateModel(
            name='device_watch_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('value_low', models.IntegerField(default=0)),
                ('value_hign', models.IntegerField(default=100)),
                ('device_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.device_type')),
            ],
            options={
                'verbose_name': '设备监控值类型表',
                'verbose_name_plural': '设备监控值类型表',
                'db_table': '设备监控值类型表',
            },
        ),
        migrations.CreateModel(
            name='device_running',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始运行时间')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.specific_device')),
                ('person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'verbose_name': '设备运行表',
                'verbose_name_plural': '设备运行表',
                'db_table': '设备运行表',
            },
        ),
        migrations.CreateModel(
            name='device_exception',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上报时间')),
                ('watch_value', models.IntegerField(default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specific_device')),
                ('person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('watch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.device_watch_type')),
            ],
            options={
                'verbose_name': '设备异常上报表',
                'verbose_name_plural': '设备异常上报表',
                'db_table': '设备异常上报表',
            },
        ),
        migrations.CreateModel(
            name='attend_training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('train_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.training_time')),
            ],
            options={
                'verbose_name': '培训参加表',
                'verbose_name_plural': '培训参加表',
                'db_table': '培训参加表',
            },
        ),
    ]
