# Generated by Django 3.2.6 on 2021-09-25 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 14, 31, 2, 773427), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
